### ISSUE TITLE
Why fully connection in Decoder?

### ISSUE THREAD

**Issue by Yitiann** [arnaghosh/Auto-Encoder#2]
Hi, I find that there are three linear and bn at the beginning of Decoder (196-200 in resnet.py). Why adding these layers? Much Thanks.

**Comment by arnaghosh** [comment]
Hi Yitiann,
I assume we tried it on a datatset and adding these linear layers seemed to help. I am not 100% sure though and @ramnagar might be able to give you a deeper insight. But from what I remember, these were hyperparameters, nothing really a hard requirement. Feel free to change them for your application. :)

**Comment by Yitiann** [comment]
Hi Arna Ghosh,
Thank you for your reply. I tried to delete them but the result became worse. I guess it is because the parameters are not enough for training such a network, without the fully connected layers. Thank you so much.

**Comment by ramnagar** [comment]
Are you still working on this?

**Comment by arnaghosh** [comment]
Not really buddy. Although I am planning to use VAEs for a course project.

**Comment by ramnagar** [comment]
Okay dude.
Best of luck.
